version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Preserve the settings database on the host filesystem
      - ./settings.db:/usr/src/app/settings.db:rw
    user: root
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_BOT_APPLICATION_ID
      - DISCORD_BOT_GUILD_ID
      - PAPERTRAIL_HOST
      - PAPERTRAIL_PORT
    command: "npm run host"
    restart: unless-stopped:0
