version: "3.7"

services:
  bot:
    user: root
    volumes:
      # Mount the source code so that we can edit it locally while it runs in the container
      - ./src/:/usr/src/app/src
    command: "npm start"
    restart: unless-stopped:0
